import type { AuditReport, Violation, Citation } from '../types'

export type SupportedLang = 'vi' | 'en'

export interface ExpertReviewData {
  id: string
  status: string
  created_at: string
  expert_summary?: string
  violation_reviews?: Array<{
    violation_index: number
    confirmed: boolean
    wording_fix?: string
    legal_note?: string
  }>
  recommended_actions?: Array<{
    action: string
    priority: string
    cfr_reference?: string
  }>
  sign_off_name?: string
  sign_off_at?: string
}

export interface PDFReportData {
  report: AuditReport
  violations: Violation[]
  generatedAt: string
  generatedBy: string // 'Vexim Compliance AI' or expert name
  companyInfo: {
    name: string
    address: string
    phone: string
    email: string
    website: string
    certificationId: string
  }
  lang?: SupportedLang
  expertReview?: ExpertReviewData | null
}

export interface PDFLabels {
  downloadTitle: string
  downloadBtn: string
  coverTitle: string
  defaultProduct: string
  reportId: string
  dateCreated: string
  result: string
  riskScore: string
  pass: string
  fail: string
  pending: string
  quickSummary: string
  critical: string
  warning: string
  info: string
  cfrCitations: string
  mainReasons: string
  generatedBy: string
  overview: string
  riskLevel: string
  overallAssessment: string
  currentRisk: string
  afterFix: string
  productInfo: string
  productName: string
  brandName: string
  category: string
  productType: string
  packageFormat: string
  netContent: string
  pdpArea: string
  manufacturer: string
  origin: string
  targetMarket: string
  detectedLangs: string
  analysisDate: string
  aiConfidence: string
  allergenDeclaration: string
  allergens: string
  ingredientList: string
  ingredientDetected: string
  nutritionInfo: string
  nutritionDetected: string
  servingSize: string
  servingsPerContainer: string
  calories: string
  totalFat: string
  saturatedFat: string
  transFat: string
  cholesterol: string
  sodium: string
  totalCarb: string
  dietaryFiber: string
  totalSugars: string
  addedSugars: string
  protein: string
  vitaminD: string
  calcium: string
  iron: string
  potassium: string
  findingsDetail: string
  noViolations: string
  noViolationsDesc: string
  legalBasis: string
  fixGuidance: string
  enforcementHistory: string
  aiConfidenceLabel: string
  riskScoreLabel: string
  enforcementFreq: string
  citationsLabel: string
  cfrSection: string
  citationContent: string
  source: string
  relevance: string
  importAlerts: string
  portRiskLabel: string
  portRiskDesc: string
  importAlertRef: string
  viewOnFda: string
  remediationSteps: string
  matchConfidence: string
  referenceOnly: string
  dwpeRedList: string
  categoryRisk: string
  technicalChecks: string
  geometryLayout: string
  issueCount: string
  expected: string
  actual: string
  colorContrast: string
  contrastDesignNote: string
  contrastRatio: string
  minimum: string
  on: string
  multiLangCompliance: string
  checks: string
  detected: string
  missingTranslations: string
  commercialSummary: string
  expertRecommendations: string
  recommendation: string
  veximAdvice: string
  portWarning: string
  portWarningDesc: string
  expertReviewNotes: string
  actionItems: string
  actionSeverity: string
  actionIssue: string
  actionRequired: string
  actionPriority: string
  seeDetails: string
  reportVerified: string
  pendingVerification: string
  upgradeTitle: string
  upgradeDesc: string
  upgradeDesc2: string
  requestVerification: string
  contactConsulting: string
  certification: string
  certificationDesc: string
  verifiedByExpert: string
  pendingExpertVerification: string
  certificationDesc2: string
  fdaComplianceExpert: string
  veximAiSystem: string
  certId: string
  disclaimer: string
  disclaimerText: string
  defaultRiskHigh: (score: string, critical: number) => string
  defaultRiskLow: (score: string) => string
  expertTipCritical: string
  expertTipWarning: string
  expertTipPass: string
  riskHigh: string
  riskMedHigh: string
  riskMed: string
  riskLow: string
  sevCritical: string
  sevWarning: string
  sevInfo: string
  tableOfContents: string
  confidenceMetrics: string
  ocrConfidence: string
  extractionConfidence: string
  legalConfidence: string
  healthClaims: string
  healthClaimsWarning: string
  verifiedNutrientClaims: string
  verifiedCompliant: string
  specialClaims: string
  enforcementInsights: string
  consequencesTitle: string
  consequenceDetention: string
  consequenceDetentionDesc: string
  consequenceRelabeling: string
  consequenceRelabelingDesc: string
  consequenceRecall: string
  consequenceRecallDesc: string
  pageFooter: string
  priorityImmediate: string
  priorityHigh: string
  priorityMedium: string
  catHealthClaims: string
  catIngredientOrder: string
  catIngredientListing: string
  catNutritionFacts: string
  catAllergenDeclaration: string
  catNetContent: string
  catCountryOfOrigin: string
  catManufacturerInfo: string
  catFontSize: string
  catLabelProminence: string
  catColorContrast: string
  catLangRequirements: string
  catMissingStatement: string
  catProhibitedClaims: string
  catDrugClaims: string
  catDiseaseClaims: string
  catStructureClaims: string
  catNutrientClaims: string
  catServingSize: string
  catDailyValue: string
  catBarcodeIssues: string
  catPackagingCompliance: string
  catImportAlertMatch: string
  catWarningLetterCitation: string
  catRecallAssociation: string
  productImages: string
  imageTypePdp: string
  imageTypeNutrition: string
  imageTypeIngredients: string
  imageTypeOther: string
  expertConsultation: string
  expertConsultationSubtitle: string
  expertOverview: string
  violationFixGuide: string
  violationConfirmed: string
  violationNotConfirmed: string
  suggestedWording: string
  expertPriorityActions: string
  priorityUrgent: string
  signedOffBy: string
  requestSentAt: string
  resultsAvailable: string
  auditScope: string
  auditScopeRegulations: string
  auditScopePanels: string
  auditScopeImages: string
  auditScopeOcrMethod: string
  auditScopeReviewDate: string
  auditScopeCfrVersion: string
  auditScopeCfrVersionValue: string
  auditScopeOcrMethodValue: string
  auditScopePanelsValue: string
  multiColumnNF: string
  multiColumnNFDesc: string
  multiColumnVariant: string
  multiColumnServingSize: string
  fdaEnforcementHistory: string
  warningLetters: string
  recalls: string
  importAlertsLabel: string
  none: string
  regulationsChecked: string
  overallAssessmentVexim: string
  conclusionLabel: string
}
